- hosts: localhost
  tasks:
    - name: ec2
      amazon.aws.ec2_instance:
        name: grupo4
        key_name: grupo4
        availability_zone: us-east-1a
        instance_type: t1.micro
        network:
          assign_public_ip: true
        image_id: ami-053b0d53c279acc90
